posts/urls.py
from django.urls import path, re_path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create', views.PostCreateView.as_view(), name='post_create'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='post_delete')
]

todos/urls.py
from django.contrib import admin
from django.urls import path, include
from todos.settings import dev
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'), name='posts')
]

urlpatterns += static(dev.STATIC_URL, document_root = dev.STATIC_ROOT)
urlpatterns += static(dev.MEDIA_URL, document_root = dev.MEDIA_ROOT)

posts/models.py
from operator import mod
from django.db import models
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='posts/',null=True, blank=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('posts:post_list')

posts/forms.py
from django import forms
from posts.models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'message','image']

posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from posts.models import Post
from posts.forms import PostCreateForm
# Create your views here.

class PostListView(ListView):
    model = Post

class PostDetailView(DetailView):
    model = Post

class PostCreateView(CreateView):
    model = Post
    form_class = PostCreateForm

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostCreateForm

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post_list')

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html'%}

{% block content %}

<form method="post">
    {% csrf_token %}

    Would you like to delete {{object}}?

    <button type="submit">Delete</button>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html'%}

{% block content %}

<h1>Post Detail Hello</h1>

<div class="card">
    <h3>{{post.title}}</h3>
    <p>{{post.message}}</p>
    <button><a href="{% url 'posts:post_delete' pk=post.pk %}">Delete</a></button>
</div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html'%}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">Submit</button>
</form>

{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html'%}
{% load static %}
{% block css_style %}
<link rel="stylesheet" href="{% static 'posts/css/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}

<h1>Post List Hello</h1>

<button><a href="{% url 'posts:post_create' %}">Create</a></button>

{% if post_list %}
    {% for post in post_list %}
        <div class="card">
            <h3><a href="{% url 'posts:post_detail' pk=post.pk %}">{{post.title}}</a> </h3>
            <p>{{post.message}}</p>
            {% if post.image %}
            <div class="img">
                <img class="w-100" src="{{post.image.url}}" alt="">
            </div>
            {% endif %}
            <button><a href="{% url 'posts:post_delete' pk=post.pk %}">Delete</a></button>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block css_style %}
    {% endblock %}
    <title>Document</title>
</head>
<body>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>